# UrlFetch Config
urlfetch:
    workerUri: ''
    timeout: 10

# Provider Configuration
# ------------------------------------------------------------------------------
providers:
    twitch:
        urls:
            api: 'https://api.twitch.tv'
            base: 'https://twitch.tv'
    kick:
        urls:
            api: 'http://127.0.0.1:9085'
            base: 'https://kick.com'
            clipUrl: 'https://kick.com/{channelId}?clip={clipId}'
    trovo:
        urls:
            api: 'https://open-api.trovo.live'
            base: 'https://trovo.live'
    picarto:
        urls:
            base: 'https://picarto.tv'

# Parser Configuration
# ------------------------------------------------------------------------------
parser:
    lastfm:
        base: 'https://ws.audioscrobbler.com/2.0/'
        key: ''
    weather:
        base: 'http://api.openweathermap.org/data/2.5/weather'
        key: ''
    pretzel:
        base: 'https://api.pretzel.tv/'
    twitter:
        base: 'https://api.twitter.com/'
        key: ''
    mastodon:
        base: ''
        key: ''
