# Provider Configs.
providers:
    twitch:
        base: 'https://twitch.tv/'
        api: 'https://api.twitch.tv/'
        clientId: ''
    glimesh:
        base: 'https://glimesh.tv/'
        api: 'https://glimesh.tv/api'
        clientId: ''
    trovo:
        base: 'https://trovo.live/'
        api: 'https://open-api.trovo.live'
        clientId: ''
    picarto:
        base: 'https://picarto.tv/'
# API Configs.
api:
    exozone:
        base: 'https://api.exozone.net/'
    lastfm:
        base: 'https://ws.audioscrobbler.com/2.0/'
        key: ''
    weather:
        base: 'http://api.openweathermap.org/data/2.5/weather'
        key: ''
    pretzel:
        base: 'https://api.pretzel.tv/'
    twitter:
        base: 'https://api.twitter.com/'
        key: ''
    mastodon:
        base: ''
        key: ''
